### ISSUE TITLE
Problems while creating a service principal

### ISSUE THREAD

**Issue by igorrfc** [bootstrapping-microservices/chapter-6#1]
Hi, when I try to run the create service principal command (`az ad sp create-for-rbac --role="Contributor" --scopes="/subscriptions/<SUB-ID>"`), I'm receiving the following error:
```sh
Insufficient privileges to complete the operation.
```

I have created my azure account exclusively for following the book's lessons, so my account has the admin role. It's weird to don't have the privileges to do that. Maybe is it because I have a basic (free) subscription and that resource requires a paid subscription now?

Thanks for the help.

**Comment by igorrfc** [comment]
I needed to enable the pay-per-use configuration to have access to the service principal resource.

**Comment by ashleydavis** [comment]
@igorrfc  Just letting you know I've started working towards a 2nd edition of Bootstrapping Microservices so I'm going to take this feedback into account.

If you have other feedback please reach out to me on ashley@codecapers.com.au.
