### ISSUE TITLE
Ch6-Page 219 | Section 6.11.2 | Git Bash on Windows | Error occurred in request., InvalidSchema: No connection adapters were found for ...

### ISSUE THREAD

**Issue by tpham210** [bootstrapping-microservices/chapter-6#2]
![image](https://user-images.githubusercontent.com/10550055/118411277-b2a25c80-b661-11eb-8cfd-94671a3abd52.png)

### https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_with_git_bash.md#auto-translation-of-resource-ids

Try:
`MSYS_NO_PATHCONV=1 az ad sp create-for-rbac --role="Contributor" --scopes="/subscriptions/<subscription-id>"`

**Comment by ashleydavis** [comment]
Thanks for letting me know.
