### ISSUE TITLE
Section 6.11.1 | Version No Longer Supported In This Region & Recommended Syntaxes for Managing Provider Versions

### ISSUE THREAD

**Issue by tpham210** [bootstrapping-microservices/chapter-6#3]
Overall, don't mess around w the version provided by the author, only change if necessary like (1).
Like the author has warned, the supported version may change when you're reading this, so make sure you check 1st.
![image](https://user-images.githubusercontent.com/10550055/118417570-a4b10380-b682-11eb-993b-2e0147adc353.png)

## (1) Version No Longer Supported In This Region 
Don't forget to rerun this cmd:
`az aks get-versions -l westus --output table`
## (2) Recommended Syntaxes for Managing Provider Versions
https://www.terraform.io/docs/language/providers/configuration.html#version-an-older-way-to-manage-provider-versions

**Comment by ashleydavis** [comment]
Thanks for your feedback.

**Comment by ashleydavis** [comment]
@tpham210  I'm going to take this feedback into account for the 2nd edition of Bootstrapping Microservices.

If you have other feedback please reach out to me on ashley@codecapers.com.au.
