### ISSUE TITLE
Getting Chapter 6 examples to work

### ISSUE THREAD

**Issue by khtan** [bootstrapping-microservices/chapter-6#4]
Hello,

Boy! I had a hard time trying to get ch6 to work just because the az-cli and terraform versions have changed so much
since the book was written. However, by installing the same version of the tool mentioned by the book, I was able to
get ch6 to work. Thanks to choco install <tool> --version=<toolversion>.

I am using Windows 10. Hopefully this helps other users when they try things out.

   | tool          |    book  | current |
   |-----------+---------+---------|
   | az-cli        |   2.9.1    |  2.30.0 |
   | terraform | 0.12.29   |  1.0.11 |
   | azurerm   |  1.38.0   |  2.79.0 |

**Comment by khtan** [comment]
I am putting this note so that other users can benefit. However, there is nothing for the author to do , so I am closing the ticket.

**Comment by ashleydavis** [comment]
@khtan Just letting you know I've started working towards a 2nd edition of Bootstrapping Microservices so I'm going to take this feedback into account.

If you have other feedback please reach out to me on ashley@codecapers.com.au.
